//Generated by TurboLink CodeGenerator, do not edit!
#include "FighterRLContext.h"
#include "SFighterrl/FighterRLClient.h"
#include "FighterRLService_Private.h"
#include "FighterRLMarshaling.h"
#include "TurboLinkGrpcManager.h"

GrpcContext_FighterService_SendState::GrpcContext_FighterService_SendState(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client)
	: Super(_Handle, _Service, _Client)
{
}

void GrpcContext_FighterService_SendState::Call(const FGrpcFighterrlAgentState& Request)
{
	check(GetState() == EGrpcContextState::Ready);
	UpdateState(EGrpcContextState::Initialing);

	::fighterrl::AgentState rpcRequest;
	TURBOLINK_TO_GRPC(&Request, &rpcRequest);

	UFighterService* service = (UFighterService*)Service;
	RpcReaderWriter = service->d->Stub->AsyncSendState(RpcContext.get(), rpcRequest, service->TurboLinkManager->d->CompletionQueue.get());
	RpcReaderWriter->ReadInitialMetadata(InitialTag);
}

void GrpcContext_FighterService_SendState::OnRpcEvent(bool Ok, const void* EventTag)
{
	Super::OnRpcEventInternal(Ok, EventTag, 
		[this](const FGrpcResult& _Result, ::fighterrl::AgentAction* _RpcResponse) 
		{
			UFighterServiceClient* client = (UFighterServiceClient*)(this->Client);
			if (!(client->OnSendStateResponse.IsBound())) return;

			FGrpcFighterrlAgentAction response;
			if (_RpcResponse) {
				GRPC_TO_TURBOLINK(_RpcResponse, &response);
			}
			client->OnSendStateResponse.Broadcast(Handle, _Result, response);
		}
	);
}
