//Generated by TurboLink CodeGenerator, do not edit!
#include "SFighterrl/FighterRLClient.h"
#include "SFighterrl/FighterRLService.h"
#include "FighterRLContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle UFighterServiceClient::InitSendState()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_FighterService_SendState>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UFighterServiceClient::SendState(FGrpcContextHandle Handle, const FGrpcFighterrlAgentState& Request, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextSendState = StaticCastSharedPtr<GrpcContext_FighterService_SendState>(*context);
		for (const auto& metaDataPair : MetaData.MetaData)
		{
			contextSendState->RpcContext->AddMetadata(
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Key)).Get(),
				(const char*)StringCast<UTF8CHAR>(*(metaDataPair.Value)).Get()
			);
		}

		if (DeadLineSeconds > 0.f)
		{
			std::chrono::time_point deadLine = std::chrono::system_clock::now() + 
				std::chrono::milliseconds((int32)(1000.f * DeadLineSeconds));
			contextSendState->RpcContext->set_deadline(deadLine);
		}
		contextSendState->Call(Request);
	}
}

void UFighterServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void UFighterServiceClient::Shutdown()
{
	OnSendStateResponse.Clear();
	Super::Shutdown();
}

