//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SFighterrl/FighterRLMessage.h"
#include "SFighterrl/FighterRLMarshaling.h"
class GrpcContext_FighterService_SendState : public GrpcContext_Ping_Pong<FighterService_SendState_ReaderWriter, ::fighterrl::AgentAction>
{
	friend class UFighterServiceClient;
	typedef GrpcContext_Ping_Pong<FighterService_SendState_ReaderWriter, ::fighterrl::AgentAction> Super;

private:
	void Call(const FGrpcFighterrlAgentState& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_FighterService_SendState(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

