//Generated by TurboLink CodeGenerator, do not edit!
#include "SFighterrl/FighterRLNode.h"
#include "SFighterrl/FighterRLService.h"
#include "TurboLinkGrpcManager.h"
#include "TurboLinkGrpcUtilities.h"
#include "Engine/World.h"
#include "TimerManager.h"
#include "Runtime/Launch/Resources/Version.h"

UCallFighterServiceSendState* UCallFighterServiceSendState::SendState(UObject* WorldContextObject, const FGrpcFighterrlAgentState& request, FGrpcMetaData metaData, float deadLineSeconds)
{
	UCallFighterServiceSendState* node = NewObject<UCallFighterServiceSendState>(WorldContextObject);
	UTurboLinkGrpcManager* turboLinkManager = UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(WorldContextObject);

	node->FighterService = Cast<UFighterService>(turboLinkManager->MakeService("FighterService"));
	if (node->FighterService == nullptr)
	{
		return nullptr;
	}
	node->ServiceState = EGrpcServiceState::Idle;
	node->Request = request;
	node->MetaData = metaData;
	node->DeadLineSeconds = deadLineSeconds;

	node->FighterService->OnServiceStateChanged.AddUniqueDynamic(node, &UCallFighterServiceSendState::OnServiceStateChanged);
	return node;
}

void UCallFighterServiceSendState::Activate()
{
	FighterService->Connect();
}

void UCallFighterServiceSendState::OnServiceStateChanged(EGrpcServiceState NewState)
{
	if (ServiceState == NewState) return;
	ServiceState = NewState;

	if (NewState == EGrpcServiceState::TransientFailure)
	{
		FGrpcResult result;
		result.Code = EGrpcResultCode::ConnectionFailed;

		FGrpcFighterrlAgentAction response;
		OnFail.Broadcast(result, response);

		Shutdown();
		return;
	}

	if (NewState == EGrpcServiceState::Ready)
	{
		FighterServiceClient = FighterService->MakeClient();
		FighterServiceClient->OnContextStateChange.AddUniqueDynamic(this, &UCallFighterServiceSendState::OnContextStateChange);
		FighterServiceClient->OnSendStateResponse.AddUniqueDynamic(this, &UCallFighterServiceSendState::OnResponse);

		Context = FighterServiceClient->InitSendState();
		FighterServiceClient->SendState(Context, Request, MetaData, DeadLineSeconds);
	}
}

void UCallFighterServiceSendState::OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State)
{
	if (State == EGrpcContextState::Done)
	{
		Shutdown();
	}
}

void UCallFighterServiceSendState::OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFighterrlAgentAction& Response)
{
	if (GrpcResult.Code == EGrpcResultCode::Ok)
	{
		OnSendStateResponse.Broadcast(GrpcResult, Response);
	}
	else
	{
		OnFail.Broadcast(GrpcResult, Response);
	}
}

void UCallFighterServiceSendState::Shutdown()
{
	FighterService->OnServiceStateChanged.RemoveDynamic(this, &UCallFighterServiceSendState::OnServiceStateChanged);
	if (FighterServiceClient != nullptr)
	{
		FighterService->RemoveClient(FighterServiceClient);
		FighterServiceClient->Shutdown();
		FighterServiceClient = nullptr;
	}

	if (FighterService != nullptr)
	{
		UTurboLinkGrpcUtilities::GetTurboLinkGrpcManager(this)->ReleaseService(FighterService);
		FighterService = nullptr;
	}

	SetReadyToDestroy();
#if ENGINE_MAJOR_VERSION>=5
	MarkAsGarbage();
#else
	MarkPendingKill();
#endif
}
