//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "SFighterrl/FighterRLMessage.h"
#include "TurboLinkGrpcContext.h"
#include "FighterRL.grpc.pb.h"

void GRPC_TO_TURBOLINK(const ::fighterrl::AgentState* in, FGrpcFighterrlAgentState* out);
void TURBOLINK_TO_GRPC(const FGrpcFighterrlAgentState* in, ::fighterrl::AgentState* out);

void GRPC_TO_TURBOLINK(const ::fighterrl::AgentAction* in, FGrpcFighterrlAgentAction* out);
void TURBOLINK_TO_GRPC(const FGrpcFighterrlAgentAction* in, ::fighterrl::AgentAction* out);

typedef grpc::ClientAsyncResponseReader<::fighterrl::AgentAction> FighterService_SendState_ReaderWriter;
