//Generated by TurboLink CodeGenerator, do not edit!
#include "SFighterrl/FighterRLMessage.h"
#include "SFighterrl/FighterRLMarshaling.h"
#include "google/protobuf/util/json_util.h"

DEFINE_JSON_FUNCTIONS(FGrpcFighterrlAgentState, ::fighterrl::AgentState)
DEFINE_JSON_FUNCTIONS(FGrpcFighterrlAgentAction, ::fighterrl::AgentAction)

