//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SFighterrl/FighterRLService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "FighterRL.grpc.pb.h"
#include "FighterRLService_Private.generated.h"

class UFighterService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::fighterrl::FighterService::Stub> Stub;
};


UCLASS()
class UFighterServiceSendStateLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UFighterServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFighterrlAgentAction& Response);
public:
	FGrpcContextHandle Handle;
	UFighterService::FSendStateResponseLambda ResponseLambda;
};

