//Generated by TurboLink CodeGenerator, do not edit!
#include "FighterRLMarshaling.h"

void GRPC_TO_TURBOLINK(const ::fighterrl::AgentState* in, FGrpcFighterrlAgentState* out)
{
    out->EnvId=StringCast<TCHAR>((const UTF8CHAR*)(in->env_id().c_str())).Get();
    out->AgentType=StringCast<TCHAR>((const UTF8CHAR*)(in->agent_type().c_str())).Get();
    out->PosX=in->pos_x();
    out->PosY=in->pos_y();
    out->PosZ=in->pos_z();
    out->RotYaw=in->rot_yaw();
    out->RotPitch=in->rot_pitch();
    out->RotRoll=in->rot_roll();
    out->VelX=in->vel_x();
    out->VelY=in->vel_y();
    out->VelZ=in->vel_z();
    out->TargetType=StringCast<TCHAR>((const UTF8CHAR*)(in->target_type().c_str())).Get();
    out->TargetDist=in->target_dist();
    out->TargetPosX=in->target_pos_x();
    out->TargetPosY=in->target_pos_y();
    out->TargetPosZ=in->target_pos_z();
    out->Reward=in->reward();
    out->Done=in->done();
}

void TURBOLINK_TO_GRPC(const FGrpcFighterrlAgentState* in, ::fighterrl::AgentState* out)
{
    out->set_env_id((const char*)StringCast<UTF8CHAR>(*(in->EnvId)).Get());
    out->set_agent_type((const char*)StringCast<UTF8CHAR>(*(in->AgentType)).Get());
    out->set_pos_x(in->PosX);
    out->set_pos_y(in->PosY);
    out->set_pos_z(in->PosZ);
    out->set_rot_yaw(in->RotYaw);
    out->set_rot_pitch(in->RotPitch);
    out->set_rot_roll(in->RotRoll);
    out->set_vel_x(in->VelX);
    out->set_vel_y(in->VelY);
    out->set_vel_z(in->VelZ);
    out->set_target_type((const char*)StringCast<UTF8CHAR>(*(in->TargetType)).Get());
    out->set_target_dist(in->TargetDist);
    out->set_target_pos_x(in->TargetPosX);
    out->set_target_pos_y(in->TargetPosY);
    out->set_target_pos_z(in->TargetPosZ);
    out->set_reward(in->Reward);
    out->set_done(in->Done);
}

void GRPC_TO_TURBOLINK(const ::fighterrl::AgentAction* in, FGrpcFighterrlAgentAction* out)
{
    out->Thrust=in->thrust();
    out->SteeringYaw=in->steering_yaw();
    out->SteeringPitch=in->steering_pitch();
    out->SteeringRoll=in->steering_roll();
    out->Fire=in->fire();
}

void TURBOLINK_TO_GRPC(const FGrpcFighterrlAgentAction* in, ::fighterrl::AgentAction* out)
{
    out->set_thrust(in->Thrust);
    out->set_steering_yaw(in->SteeringYaw);
    out->set_steering_pitch(in->SteeringPitch);
    out->set_steering_roll(in->SteeringRoll);
    out->set_fire(in->Fire);
}

