//Generated by TurboLink CodeGenerator, do not edit!
#include "SFighterrl/FighterRLService.h"
#include "SFighterrl/FighterRLClient.h"
#include "FighterRLService_Private.h"
#include "FighterRLMarshaling.h"
#include "TurboLinkGrpcManager_Private.h"
#include "TurboLinkGrpcUtilities.h"

UFighterService::UFighterService()
	: d(new UFighterService::Private())
{
}

UFighterService::~UFighterService()
{
	delete d;
}

void UFighterService::Connect()
{
	FString serviceEndPoint = UTurboLinkGrpcUtilities::GetTurboLinkGrpcConfig()->GetServiceEndPoint(TEXT("FighterService"));
	UE_LOG(LogTurboLink, Warning, TEXT("Connect to FighterService: '%s'"), *serviceEndPoint);

	if (d->Channel == nullptr) {
		d->Channel = TurboLinkManager->d->CreateServiceChannel((const char*)StringCast<UTF8CHAR>(*serviceEndPoint).Get(), this);
	}
	if (d->Stub == nullptr) {
		d->Stub = fighterrl::FighterService::NewStub(d->Channel->RpcChannel);
	}

	grpc_connectivity_state currentChannelState = d->Channel->RpcChannel->GetState(true);
	if (OnServiceStateChanged.IsBound())
	{
		OnServiceStateChanged.Broadcast(UTurboLinkGrpcManager::Private::GrpcStateToServiceState(currentChannelState));
	}
}

EGrpcServiceState UFighterService::GetServiceState() const
{
	if (d->Channel == nullptr) return EGrpcServiceState::NotCreate;

	auto rpcChannelState = d->Channel->RpcChannel->GetState(false);
	return UTurboLinkGrpcManager::Private::GrpcStateToServiceState(rpcChannelState);
}

UFighterServiceClient* UFighterService::MakeClient()
{
	auto client = UGrpcService::MakeClient<UFighterServiceClient>();
	return client;
}

void UFighterService::Shutdown()
{
	Super::Shutdown();
	d->Stub = nullptr;
	if (d->Channel != nullptr) {
		TurboLinkManager->d->RemoveServiceChannel(d->Channel, this);
		d->Channel = nullptr;
	}
}

void UFighterService::CallSendState(const FGrpcFighterrlAgentState& Request, FSendStateResponseLambda ResponseLambda, FGrpcMetaData MetaData, float DeadLineSeconds)
{
	if (InnerClient == nullptr)
	{
		InnerClient = MakeClient();
	}
	UFighterServiceSendStateLambdaWrapper* lambdaWrapper = NewObject<UFighterServiceSendStateLambdaWrapper>();
	lambdaWrapper->InnerClient = InnerClient;
	lambdaWrapper->ResponseLambda = ResponseLambda;
	lambdaWrapper->Handle = InnerClient->InitSendState();
	InnerClient->OnSendStateResponse.AddUniqueDynamic(lambdaWrapper, &UFighterServiceSendStateLambdaWrapper::OnResponse);
	InnerClient->SendState(lambdaWrapper->Handle, Request, MetaData, DeadLineSeconds);
}
