//Generated by TurboLink CodeGenerator, do not edit!
#include "FighterRLService_Private.h"

void UFighterServiceSendStateLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcFighterrlAgentAction& Response)
{
	if (_Handle != this->Handle) return;

	ResponseLambda(GrpcResult, Response);
	InnerClient->OnSendStateResponse.RemoveDynamic(this, &UFighterServiceSendStateLambdaWrapper::OnResponse);
}

