# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FighterRL.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'FighterRL.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x46ighterRL.proto\x12\tfighterrl\"\xca\x02\n\nAgentState\x12\x0e\n\x06\x65nv_id\x18\x01 \x01(\t\x12\x12\n\nagent_type\x18\x02 \x01(\t\x12\r\n\x05pos_x\x18\x03 \x01(\x02\x12\r\n\x05pos_y\x18\x04 \x01(\x02\x12\r\n\x05pos_z\x18\x05 \x01(\x02\x12\x0f\n\x07rot_yaw\x18\x06 \x01(\x02\x12\x11\n\trot_pitch\x18\x07 \x01(\x02\x12\x10\n\x08rot_roll\x18\x08 \x01(\x02\x12\r\n\x05vel_x\x18\t \x01(\x02\x12\r\n\x05vel_y\x18\n \x01(\x02\x12\r\n\x05vel_z\x18\x0b \x01(\x02\x12\x13\n\x0btarget_type\x18\x0c \x01(\t\x12\x13\n\x0btarget_dist\x18\r \x01(\x02\x12\x14\n\x0ctarget_pos_x\x18\x0e \x01(\x02\x12\x14\n\x0ctarget_pos_y\x18\x0f \x01(\x02\x12\x14\n\x0ctarget_pos_z\x18\x10 \x01(\x02\x12\x0e\n\x06reward\x18\x11 \x01(\x02\x12\x0c\n\x04\x64one\x18\x12 \x01(\x08\"p\n\x0b\x41gentAction\x12\x0e\n\x06thrust\x18\x01 \x01(\x02\x12\x14\n\x0csteering_yaw\x18\x02 \x01(\x02\x12\x16\n\x0esteering_pitch\x18\x03 \x01(\x02\x12\x15\n\rsteering_roll\x18\x04 \x01(\x02\x12\x0c\n\x04\x66ire\x18\x05 \x01(\x08\x32L\n\x0e\x46ighterService\x12:\n\tSendState\x12\x15.fighterrl.AgentState\x1a\x16.fighterrl.AgentActionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FighterRL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTSTATE']._serialized_start=31
  _globals['_AGENTSTATE']._serialized_end=361
  _globals['_AGENTACTION']._serialized_start=363
  _globals['_AGENTACTION']._serialized_end=475
  _globals['_FIGHTERSERVICE']._serialized_start=477
  _globals['_FIGHTERSERVICE']._serialized_end=553
# @@protoc_insertion_point(module_scope)
