//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "FighterRLMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Fighterrl.AgentState"))
struct FGrpcFighterrlAgentState : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString EnvId = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString AgentType = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float PosX = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float PosY = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float PosZ = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float RotYaw = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float RotPitch = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float RotRoll = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float VelX = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float VelY = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float VelZ = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    FString TargetType = "";

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float TargetDist = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float TargetPosX = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float TargetPosY = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float TargetPosZ = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Reward = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Done = false;
};

USTRUCT(BlueprintType, meta = (DisplayName="Fighterrl.AgentAction"))
struct FGrpcFighterrlAgentAction : public FGrpcMessage
{
    GENERATED_BODY()
    DECLARE_JSON_FUNCTIONS()

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float Thrust = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float SteeringYaw = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float SteeringPitch = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    float SteeringRoll = 0;

    UPROPERTY(BlueprintReadWrite, Category = TurboLink)
    bool Fire = false;
};
