//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "FighterRLMessage.h"
#include "FighterRLNode.generated.h"

class UFighterService;
class UFighterServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallFighterServiceSendState : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FFighterServiceSendStateDelegate, const FGrpcResult&, GrpcResult, const FGrpcFighterrlAgentAction&, Response);

	UFUNCTION(BlueprintCallable, Category = "TurboLink|FighterService", meta = (
		BlueprintInternalUseOnly = "true",
		WorldContext = "WorldContextObject",
		DisplayName = "Call FighterService SendState",
		AdvancedDisplay = 2))
	static UCallFighterServiceSendState* SendState(UObject* WorldContextObject, const FGrpcFighterrlAgentState& request, FGrpcMetaData metaData = FGrpcMetaData(), float deadLineSeconds = 0.f);

	UPROPERTY(BlueprintAssignable)
	FFighterServiceSendStateDelegate OnSendStateResponse;

	UPROPERTY(BlueprintAssignable)
	FFighterServiceSendStateDelegate OnFail;

private:
	virtual void Activate() override;

	UPROPERTY()
	UFighterService* FighterService;
	
	UPROPERTY()
	UFighterServiceClient* FighterServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcFighterrlAgentState Request;
	EGrpcServiceState ServiceState;
	FGrpcMetaData MetaData;
	float DeadLineSeconds;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcFighterrlAgentAction& Response);

	void Shutdown();
};
