#if defined(_MSC_VER)
  #pragma warning (disable:4018) // 'expression' : signed/unsigned mismatch
  #pragma warning (disable:4065) // switch statement contains 'default' but no 'case' labels
  #pragma warning (disable:4146) // unary minus operator applied to unsigned type, result still unsigned
  #pragma warning (disable:4244) // 'conversion' conversion from 'type1' to 'type2', possible loss of data
  #pragma warning (disable:4251) // 'identifier' : class 'type' needs to have dll-interface to be used by clients of class 'type2'
  #pragma warning (disable:4267) // 'var' : conversion from 'size_t' to 'type', possible loss of data
  #pragma warning (disable:4305) // 'identifier' : truncation from 'type1' to 'type2'
  #pragma warning (disable:4307) // 'operator' : integral constant overflow
  #pragma warning (disable:4309) // 'conversion' : truncation of constant value
  #pragma warning (disable:4334) // 'operator' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
  #pragma warning (disable:4355) // 'this' : used in base member initializer list
  #pragma warning (disable:4506) // no definition for inline function 'function'
  #pragma warning (disable:4996) // The compiler encountered a deprecated declaration.
  #pragma warning (disable:4125) // decimal digit terminates octal escape sequence
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FighterRL.proto

#include "FighterRL.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace fighterrl {
template <typename>
PROTOBUF_CONSTEXPR AgentState::AgentState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.env_id_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.agent_type_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.target_type_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.pos_x_)*/ 0

  , /*decltype(_impl_.pos_y_)*/ 0

  , /*decltype(_impl_.pos_z_)*/ 0

  , /*decltype(_impl_.rot_yaw_)*/ 0

  , /*decltype(_impl_.rot_pitch_)*/ 0

  , /*decltype(_impl_.rot_roll_)*/ 0

  , /*decltype(_impl_.vel_x_)*/ 0

  , /*decltype(_impl_.vel_y_)*/ 0

  , /*decltype(_impl_.vel_z_)*/ 0

  , /*decltype(_impl_.target_dist_)*/ 0

  , /*decltype(_impl_.target_pos_x_)*/ 0

  , /*decltype(_impl_.target_pos_y_)*/ 0

  , /*decltype(_impl_.target_pos_z_)*/ 0

  , /*decltype(_impl_.reward_)*/ 0

  , /*decltype(_impl_.done_)*/ false

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgentStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentStateDefaultTypeInternal() {}
  union {
    AgentState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentStateDefaultTypeInternal _AgentState_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR AgentAction::AgentAction(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.thrust_)*/ 0

  , /*decltype(_impl_.steering_yaw_)*/ 0

  , /*decltype(_impl_.steering_pitch_)*/ 0

  , /*decltype(_impl_.steering_roll_)*/ 0

  , /*decltype(_impl_.fire_)*/ false

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgentActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentActionDefaultTypeInternal() {}
  union {
    AgentAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentActionDefaultTypeInternal _AgentAction_default_instance_;
}  // namespace fighterrl
static ::_pb::Metadata file_level_metadata_FighterRL_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_FighterRL_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_FighterRL_2eproto = nullptr;
const ::uint32_t TableStruct_FighterRL_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.env_id_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.agent_type_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.pos_x_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.pos_y_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.pos_z_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.rot_yaw_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.rot_pitch_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.rot_roll_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.vel_x_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.vel_y_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.vel_z_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.target_type_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.target_dist_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.target_pos_x_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.target_pos_y_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.target_pos_z_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.reward_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentState, _impl_.done_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentAction, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentAction, _impl_.thrust_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentAction, _impl_.steering_yaw_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentAction, _impl_.steering_pitch_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentAction, _impl_.steering_roll_),
    PROTOBUF_FIELD_OFFSET(::fighterrl::AgentAction, _impl_.fire_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::fighterrl::AgentState)},
        { 26, -1, -1, sizeof(::fighterrl::AgentAction)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::fighterrl::_AgentState_default_instance_._instance,
    &::fighterrl::_AgentAction_default_instance_._instance,
};
const char descriptor_table_protodef_FighterRL_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017FighterRL.proto\022\tfighterrl\"\312\002\n\nAgentSt"
    "ate\022\016\n\006env_id\030\001 \001(\t\022\022\n\nagent_type\030\002 \001(\t\022"
    "\r\n\005pos_x\030\003 \001(\002\022\r\n\005pos_y\030\004 \001(\002\022\r\n\005pos_z\030\005"
    " \001(\002\022\017\n\007rot_yaw\030\006 \001(\002\022\021\n\trot_pitch\030\007 \001(\002"
    "\022\020\n\010rot_roll\030\010 \001(\002\022\r\n\005vel_x\030\t \001(\002\022\r\n\005vel"
    "_y\030\n \001(\002\022\r\n\005vel_z\030\013 \001(\002\022\023\n\013target_type\030\014"
    " \001(\t\022\023\n\013target_dist\030\r \001(\002\022\024\n\014target_pos_"
    "x\030\016 \001(\002\022\024\n\014target_pos_y\030\017 \001(\002\022\024\n\014target_"
    "pos_z\030\020 \001(\002\022\016\n\006reward\030\021 \001(\002\022\014\n\004done\030\022 \001("
    "\010\"p\n\013AgentAction\022\016\n\006thrust\030\001 \001(\002\022\024\n\014stee"
    "ring_yaw\030\002 \001(\002\022\026\n\016steering_pitch\030\003 \001(\002\022\025"
    "\n\rsteering_roll\030\004 \001(\002\022\014\n\004fire\030\005 \001(\0102L\n\016F"
    "ighterService\022:\n\tSendState\022\025.fighterrl.A"
    "gentState\032\026.fighterrl.AgentActionb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_FighterRL_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_FighterRL_2eproto = {
    false,
    false,
    561,
    descriptor_table_protodef_FighterRL_2eproto,
    "FighterRL.proto",
    &descriptor_table_FighterRL_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_FighterRL_2eproto::offsets,
    file_level_metadata_FighterRL_2eproto,
    file_level_enum_descriptors_FighterRL_2eproto,
    file_level_service_descriptors_FighterRL_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_FighterRL_2eproto_getter() {
  return &descriptor_table_FighterRL_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_FighterRL_2eproto(&descriptor_table_FighterRL_2eproto);
namespace fighterrl {
// ===================================================================

class AgentState::_Internal {
 public:
};

AgentState::AgentState(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:fighterrl.AgentState)
}
AgentState::AgentState(const AgentState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AgentState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.env_id_) {}

    , decltype(_impl_.agent_type_) {}

    , decltype(_impl_.target_type_) {}

    , decltype(_impl_.pos_x_) {}

    , decltype(_impl_.pos_y_) {}

    , decltype(_impl_.pos_z_) {}

    , decltype(_impl_.rot_yaw_) {}

    , decltype(_impl_.rot_pitch_) {}

    , decltype(_impl_.rot_roll_) {}

    , decltype(_impl_.vel_x_) {}

    , decltype(_impl_.vel_y_) {}

    , decltype(_impl_.vel_z_) {}

    , decltype(_impl_.target_dist_) {}

    , decltype(_impl_.target_pos_x_) {}

    , decltype(_impl_.target_pos_y_) {}

    , decltype(_impl_.target_pos_z_) {}

    , decltype(_impl_.reward_) {}

    , decltype(_impl_.done_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.env_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.env_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_env_id().empty()) {
    _this->_impl_.env_id_.Set(from._internal_env_id(), _this->GetArenaForAllocation());
  }
  _impl_.agent_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.agent_type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_agent_type().empty()) {
    _this->_impl_.agent_type_.Set(from._internal_agent_type(), _this->GetArenaForAllocation());
  }
  _impl_.target_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.target_type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_target_type().empty()) {
    _this->_impl_.target_type_.Set(from._internal_target_type(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.pos_x_, &from._impl_.pos_x_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.done_) -
    reinterpret_cast<char*>(&_impl_.pos_x_)) + sizeof(_impl_.done_));
  // @@protoc_insertion_point(copy_constructor:fighterrl.AgentState)
}

inline void AgentState::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.env_id_) {}

    , decltype(_impl_.agent_type_) {}

    , decltype(_impl_.target_type_) {}

    , decltype(_impl_.pos_x_) { 0 }

    , decltype(_impl_.pos_y_) { 0 }

    , decltype(_impl_.pos_z_) { 0 }

    , decltype(_impl_.rot_yaw_) { 0 }

    , decltype(_impl_.rot_pitch_) { 0 }

    , decltype(_impl_.rot_roll_) { 0 }

    , decltype(_impl_.vel_x_) { 0 }

    , decltype(_impl_.vel_y_) { 0 }

    , decltype(_impl_.vel_z_) { 0 }

    , decltype(_impl_.target_dist_) { 0 }

    , decltype(_impl_.target_pos_x_) { 0 }

    , decltype(_impl_.target_pos_y_) { 0 }

    , decltype(_impl_.target_pos_z_) { 0 }

    , decltype(_impl_.reward_) { 0 }

    , decltype(_impl_.done_) { false }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.env_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.env_id_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.agent_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.agent_type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.target_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.target_type_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AgentState::~AgentState() {
  // @@protoc_insertion_point(destructor:fighterrl.AgentState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AgentState::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.env_id_.Destroy();
  _impl_.agent_type_.Destroy();
  _impl_.target_type_.Destroy();
}

void AgentState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgentState::Clear() {
// @@protoc_insertion_point(message_clear_start:fighterrl.AgentState)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.env_id_.ClearToEmpty();
  _impl_.agent_type_.ClearToEmpty();
  _impl_.target_type_.ClearToEmpty();
  ::memset(&_impl_.pos_x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.done_) -
      reinterpret_cast<char*>(&_impl_.pos_x_)) + sizeof(_impl_.done_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgentState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string env_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_env_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fighterrl.AgentState.env_id"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string agent_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_agent_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fighterrl.AgentState.agent_type"));
        } else {
          goto handle_unusual;
        }
        continue;
      // float pos_x = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 29)) {
          _impl_.pos_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float pos_y = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 37)) {
          _impl_.pos_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float pos_z = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 45)) {
          _impl_.pos_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float rot_yaw = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 53)) {
          _impl_.rot_yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float rot_pitch = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 61)) {
          _impl_.rot_pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float rot_roll = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 69)) {
          _impl_.rot_roll_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float vel_x = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 77)) {
          _impl_.vel_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float vel_y = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 85)) {
          _impl_.vel_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float vel_z = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 93)) {
          _impl_.vel_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // string target_type = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 98)) {
          auto str = _internal_mutable_target_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "fighterrl.AgentState.target_type"));
        } else {
          goto handle_unusual;
        }
        continue;
      // float target_dist = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 109)) {
          _impl_.target_dist_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float target_pos_x = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 117)) {
          _impl_.target_pos_x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float target_pos_y = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 125)) {
          _impl_.target_pos_y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float target_pos_z = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 133)) {
          _impl_.target_pos_z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float reward = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 141)) {
          _impl_.reward_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // bool done = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 144)) {
          _impl_.done_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AgentState::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fighterrl.AgentState)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string env_id = 1;
  if (!this->_internal_env_id().empty()) {
    const std::string& _s = this->_internal_env_id();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "fighterrl.AgentState.env_id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string agent_type = 2;
  if (!this->_internal_agent_type().empty()) {
    const std::string& _s = this->_internal_agent_type();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "fighterrl.AgentState.agent_type");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // float pos_x = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_x = this->_internal_pos_x();
  ::uint32_t raw_pos_x;
  memcpy(&raw_pos_x, &tmp_pos_x, sizeof(tmp_pos_x));
  if (raw_pos_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_pos_x(), target);
  }

  // float pos_y = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_y = this->_internal_pos_y();
  ::uint32_t raw_pos_y;
  memcpy(&raw_pos_y, &tmp_pos_y, sizeof(tmp_pos_y));
  if (raw_pos_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_pos_y(), target);
  }

  // float pos_z = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_z = this->_internal_pos_z();
  ::uint32_t raw_pos_z;
  memcpy(&raw_pos_z, &tmp_pos_z, sizeof(tmp_pos_z));
  if (raw_pos_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_pos_z(), target);
  }

  // float rot_yaw = 6;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_yaw = this->_internal_rot_yaw();
  ::uint32_t raw_rot_yaw;
  memcpy(&raw_rot_yaw, &tmp_rot_yaw, sizeof(tmp_rot_yaw));
  if (raw_rot_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this->_internal_rot_yaw(), target);
  }

  // float rot_pitch = 7;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_pitch = this->_internal_rot_pitch();
  ::uint32_t raw_rot_pitch;
  memcpy(&raw_rot_pitch, &tmp_rot_pitch, sizeof(tmp_rot_pitch));
  if (raw_rot_pitch != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        7, this->_internal_rot_pitch(), target);
  }

  // float rot_roll = 8;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_roll = this->_internal_rot_roll();
  ::uint32_t raw_rot_roll;
  memcpy(&raw_rot_roll, &tmp_rot_roll, sizeof(tmp_rot_roll));
  if (raw_rot_roll != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        8, this->_internal_rot_roll(), target);
  }

  // float vel_x = 9;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_x = this->_internal_vel_x();
  ::uint32_t raw_vel_x;
  memcpy(&raw_vel_x, &tmp_vel_x, sizeof(tmp_vel_x));
  if (raw_vel_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        9, this->_internal_vel_x(), target);
  }

  // float vel_y = 10;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_y = this->_internal_vel_y();
  ::uint32_t raw_vel_y;
  memcpy(&raw_vel_y, &tmp_vel_y, sizeof(tmp_vel_y));
  if (raw_vel_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        10, this->_internal_vel_y(), target);
  }

  // float vel_z = 11;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_z = this->_internal_vel_z();
  ::uint32_t raw_vel_z;
  memcpy(&raw_vel_z, &tmp_vel_z, sizeof(tmp_vel_z));
  if (raw_vel_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        11, this->_internal_vel_z(), target);
  }

  // string target_type = 12;
  if (!this->_internal_target_type().empty()) {
    const std::string& _s = this->_internal_target_type();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "fighterrl.AgentState.target_type");
    target = stream->WriteStringMaybeAliased(12, _s, target);
  }

  // float target_dist = 13;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_dist = this->_internal_target_dist();
  ::uint32_t raw_target_dist;
  memcpy(&raw_target_dist, &tmp_target_dist, sizeof(tmp_target_dist));
  if (raw_target_dist != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        13, this->_internal_target_dist(), target);
  }

  // float target_pos_x = 14;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_x = this->_internal_target_pos_x();
  ::uint32_t raw_target_pos_x;
  memcpy(&raw_target_pos_x, &tmp_target_pos_x, sizeof(tmp_target_pos_x));
  if (raw_target_pos_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        14, this->_internal_target_pos_x(), target);
  }

  // float target_pos_y = 15;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_y = this->_internal_target_pos_y();
  ::uint32_t raw_target_pos_y;
  memcpy(&raw_target_pos_y, &tmp_target_pos_y, sizeof(tmp_target_pos_y));
  if (raw_target_pos_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        15, this->_internal_target_pos_y(), target);
  }

  // float target_pos_z = 16;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_z = this->_internal_target_pos_z();
  ::uint32_t raw_target_pos_z;
  memcpy(&raw_target_pos_z, &tmp_target_pos_z, sizeof(tmp_target_pos_z));
  if (raw_target_pos_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        16, this->_internal_target_pos_z(), target);
  }

  // float reward = 17;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_reward = this->_internal_reward();
  ::uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        17, this->_internal_reward(), target);
  }

  // bool done = 18;
  if (this->_internal_done() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        18, this->_internal_done(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fighterrl.AgentState)
  return target;
}

::size_t AgentState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fighterrl.AgentState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string env_id = 1;
  if (!this->_internal_env_id().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_env_id());
  }

  // string agent_type = 2;
  if (!this->_internal_agent_type().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_agent_type());
  }

  // string target_type = 12;
  if (!this->_internal_target_type().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_target_type());
  }

  // float pos_x = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_x = this->_internal_pos_x();
  ::uint32_t raw_pos_x;
  memcpy(&raw_pos_x, &tmp_pos_x, sizeof(tmp_pos_x));
  if (raw_pos_x != 0) {
    total_size += 5;
  }

  // float pos_y = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_y = this->_internal_pos_y();
  ::uint32_t raw_pos_y;
  memcpy(&raw_pos_y, &tmp_pos_y, sizeof(tmp_pos_y));
  if (raw_pos_y != 0) {
    total_size += 5;
  }

  // float pos_z = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_z = this->_internal_pos_z();
  ::uint32_t raw_pos_z;
  memcpy(&raw_pos_z, &tmp_pos_z, sizeof(tmp_pos_z));
  if (raw_pos_z != 0) {
    total_size += 5;
  }

  // float rot_yaw = 6;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_yaw = this->_internal_rot_yaw();
  ::uint32_t raw_rot_yaw;
  memcpy(&raw_rot_yaw, &tmp_rot_yaw, sizeof(tmp_rot_yaw));
  if (raw_rot_yaw != 0) {
    total_size += 5;
  }

  // float rot_pitch = 7;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_pitch = this->_internal_rot_pitch();
  ::uint32_t raw_rot_pitch;
  memcpy(&raw_rot_pitch, &tmp_rot_pitch, sizeof(tmp_rot_pitch));
  if (raw_rot_pitch != 0) {
    total_size += 5;
  }

  // float rot_roll = 8;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_roll = this->_internal_rot_roll();
  ::uint32_t raw_rot_roll;
  memcpy(&raw_rot_roll, &tmp_rot_roll, sizeof(tmp_rot_roll));
  if (raw_rot_roll != 0) {
    total_size += 5;
  }

  // float vel_x = 9;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_x = this->_internal_vel_x();
  ::uint32_t raw_vel_x;
  memcpy(&raw_vel_x, &tmp_vel_x, sizeof(tmp_vel_x));
  if (raw_vel_x != 0) {
    total_size += 5;
  }

  // float vel_y = 10;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_y = this->_internal_vel_y();
  ::uint32_t raw_vel_y;
  memcpy(&raw_vel_y, &tmp_vel_y, sizeof(tmp_vel_y));
  if (raw_vel_y != 0) {
    total_size += 5;
  }

  // float vel_z = 11;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_z = this->_internal_vel_z();
  ::uint32_t raw_vel_z;
  memcpy(&raw_vel_z, &tmp_vel_z, sizeof(tmp_vel_z));
  if (raw_vel_z != 0) {
    total_size += 5;
  }

  // float target_dist = 13;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_dist = this->_internal_target_dist();
  ::uint32_t raw_target_dist;
  memcpy(&raw_target_dist, &tmp_target_dist, sizeof(tmp_target_dist));
  if (raw_target_dist != 0) {
    total_size += 5;
  }

  // float target_pos_x = 14;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_x = this->_internal_target_pos_x();
  ::uint32_t raw_target_pos_x;
  memcpy(&raw_target_pos_x, &tmp_target_pos_x, sizeof(tmp_target_pos_x));
  if (raw_target_pos_x != 0) {
    total_size += 5;
  }

  // float target_pos_y = 15;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_y = this->_internal_target_pos_y();
  ::uint32_t raw_target_pos_y;
  memcpy(&raw_target_pos_y, &tmp_target_pos_y, sizeof(tmp_target_pos_y));
  if (raw_target_pos_y != 0) {
    total_size += 5;
  }

  // float target_pos_z = 16;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_z = this->_internal_target_pos_z();
  ::uint32_t raw_target_pos_z;
  memcpy(&raw_target_pos_z, &tmp_target_pos_z, sizeof(tmp_target_pos_z));
  if (raw_target_pos_z != 0) {
    total_size += 6;
  }

  // float reward = 17;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_reward = this->_internal_reward();
  ::uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    total_size += 6;
  }

  // bool done = 18;
  if (this->_internal_done() != 0) {
    total_size += 3;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgentState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgentState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgentState::GetClassData() const { return &_class_data_; }


void AgentState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgentState*>(&to_msg);
  auto& from = static_cast<const AgentState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fighterrl.AgentState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_env_id().empty()) {
    _this->_internal_set_env_id(from._internal_env_id());
  }
  if (!from._internal_agent_type().empty()) {
    _this->_internal_set_agent_type(from._internal_agent_type());
  }
  if (!from._internal_target_type().empty()) {
    _this->_internal_set_target_type(from._internal_target_type());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_x = from._internal_pos_x();
  ::uint32_t raw_pos_x;
  memcpy(&raw_pos_x, &tmp_pos_x, sizeof(tmp_pos_x));
  if (raw_pos_x != 0) {
    _this->_internal_set_pos_x(from._internal_pos_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_y = from._internal_pos_y();
  ::uint32_t raw_pos_y;
  memcpy(&raw_pos_y, &tmp_pos_y, sizeof(tmp_pos_y));
  if (raw_pos_y != 0) {
    _this->_internal_set_pos_y(from._internal_pos_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_pos_z = from._internal_pos_z();
  ::uint32_t raw_pos_z;
  memcpy(&raw_pos_z, &tmp_pos_z, sizeof(tmp_pos_z));
  if (raw_pos_z != 0) {
    _this->_internal_set_pos_z(from._internal_pos_z());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_yaw = from._internal_rot_yaw();
  ::uint32_t raw_rot_yaw;
  memcpy(&raw_rot_yaw, &tmp_rot_yaw, sizeof(tmp_rot_yaw));
  if (raw_rot_yaw != 0) {
    _this->_internal_set_rot_yaw(from._internal_rot_yaw());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_pitch = from._internal_rot_pitch();
  ::uint32_t raw_rot_pitch;
  memcpy(&raw_rot_pitch, &tmp_rot_pitch, sizeof(tmp_rot_pitch));
  if (raw_rot_pitch != 0) {
    _this->_internal_set_rot_pitch(from._internal_rot_pitch());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_rot_roll = from._internal_rot_roll();
  ::uint32_t raw_rot_roll;
  memcpy(&raw_rot_roll, &tmp_rot_roll, sizeof(tmp_rot_roll));
  if (raw_rot_roll != 0) {
    _this->_internal_set_rot_roll(from._internal_rot_roll());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_x = from._internal_vel_x();
  ::uint32_t raw_vel_x;
  memcpy(&raw_vel_x, &tmp_vel_x, sizeof(tmp_vel_x));
  if (raw_vel_x != 0) {
    _this->_internal_set_vel_x(from._internal_vel_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_y = from._internal_vel_y();
  ::uint32_t raw_vel_y;
  memcpy(&raw_vel_y, &tmp_vel_y, sizeof(tmp_vel_y));
  if (raw_vel_y != 0) {
    _this->_internal_set_vel_y(from._internal_vel_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_vel_z = from._internal_vel_z();
  ::uint32_t raw_vel_z;
  memcpy(&raw_vel_z, &tmp_vel_z, sizeof(tmp_vel_z));
  if (raw_vel_z != 0) {
    _this->_internal_set_vel_z(from._internal_vel_z());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_dist = from._internal_target_dist();
  ::uint32_t raw_target_dist;
  memcpy(&raw_target_dist, &tmp_target_dist, sizeof(tmp_target_dist));
  if (raw_target_dist != 0) {
    _this->_internal_set_target_dist(from._internal_target_dist());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_x = from._internal_target_pos_x();
  ::uint32_t raw_target_pos_x;
  memcpy(&raw_target_pos_x, &tmp_target_pos_x, sizeof(tmp_target_pos_x));
  if (raw_target_pos_x != 0) {
    _this->_internal_set_target_pos_x(from._internal_target_pos_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_y = from._internal_target_pos_y();
  ::uint32_t raw_target_pos_y;
  memcpy(&raw_target_pos_y, &tmp_target_pos_y, sizeof(tmp_target_pos_y));
  if (raw_target_pos_y != 0) {
    _this->_internal_set_target_pos_y(from._internal_target_pos_y());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_target_pos_z = from._internal_target_pos_z();
  ::uint32_t raw_target_pos_z;
  memcpy(&raw_target_pos_z, &tmp_target_pos_z, sizeof(tmp_target_pos_z));
  if (raw_target_pos_z != 0) {
    _this->_internal_set_target_pos_z(from._internal_target_pos_z());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_reward = from._internal_reward();
  ::uint32_t raw_reward;
  memcpy(&raw_reward, &tmp_reward, sizeof(tmp_reward));
  if (raw_reward != 0) {
    _this->_internal_set_reward(from._internal_reward());
  }
  if (from._internal_done() != 0) {
    _this->_internal_set_done(from._internal_done());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgentState::CopyFrom(const AgentState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fighterrl.AgentState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgentState::IsInitialized() const {
  return true;
}

void AgentState::InternalSwap(AgentState* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.env_id_, lhs_arena,
                                       &other->_impl_.env_id_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.agent_type_, lhs_arena,
                                       &other->_impl_.agent_type_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.target_type_, lhs_arena,
                                       &other->_impl_.target_type_, rhs_arena);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AgentState, _impl_.done_)
      + sizeof(AgentState::_impl_.done_)
      - PROTOBUF_FIELD_OFFSET(AgentState, _impl_.pos_x_)>(
          reinterpret_cast<char*>(&_impl_.pos_x_),
          reinterpret_cast<char*>(&other->_impl_.pos_x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AgentState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_FighterRL_2eproto_getter, &descriptor_table_FighterRL_2eproto_once,
      file_level_metadata_FighterRL_2eproto[0]);
}
// ===================================================================

class AgentAction::_Internal {
 public:
};

AgentAction::AgentAction(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:fighterrl.AgentAction)
}
AgentAction::AgentAction(const AgentAction& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:fighterrl.AgentAction)
}

inline void AgentAction::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.thrust_) { 0 }

    , decltype(_impl_.steering_yaw_) { 0 }

    , decltype(_impl_.steering_pitch_) { 0 }

    , decltype(_impl_.steering_roll_) { 0 }

    , decltype(_impl_.fire_) { false }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AgentAction::~AgentAction() {
  // @@protoc_insertion_point(destructor:fighterrl.AgentAction)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AgentAction::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void AgentAction::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgentAction::Clear() {
// @@protoc_insertion_point(message_clear_start:fighterrl.AgentAction)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.thrust_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.fire_) -
      reinterpret_cast<char*>(&_impl_.thrust_)) + sizeof(_impl_.fire_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgentAction::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float thrust = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 13)) {
          _impl_.thrust_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float steering_yaw = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 21)) {
          _impl_.steering_yaw_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float steering_pitch = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 29)) {
          _impl_.steering_pitch_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // float steering_roll = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 37)) {
          _impl_.steering_roll_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else {
          goto handle_unusual;
        }
        continue;
      // bool fire = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          _impl_.fire_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* AgentAction::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:fighterrl.AgentAction)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float thrust = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_thrust = this->_internal_thrust();
  ::uint32_t raw_thrust;
  memcpy(&raw_thrust, &tmp_thrust, sizeof(tmp_thrust));
  if (raw_thrust != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_thrust(), target);
  }

  // float steering_yaw = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_yaw = this->_internal_steering_yaw();
  ::uint32_t raw_steering_yaw;
  memcpy(&raw_steering_yaw, &tmp_steering_yaw, sizeof(tmp_steering_yaw));
  if (raw_steering_yaw != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this->_internal_steering_yaw(), target);
  }

  // float steering_pitch = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pitch = this->_internal_steering_pitch();
  ::uint32_t raw_steering_pitch;
  memcpy(&raw_steering_pitch, &tmp_steering_pitch, sizeof(tmp_steering_pitch));
  if (raw_steering_pitch != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_steering_pitch(), target);
  }

  // float steering_roll = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_roll = this->_internal_steering_roll();
  ::uint32_t raw_steering_roll;
  memcpy(&raw_steering_roll, &tmp_steering_roll, sizeof(tmp_steering_roll));
  if (raw_steering_roll != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_steering_roll(), target);
  }

  // bool fire = 5;
  if (this->_internal_fire() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        5, this->_internal_fire(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:fighterrl.AgentAction)
  return target;
}

::size_t AgentAction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:fighterrl.AgentAction)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float thrust = 1;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_thrust = this->_internal_thrust();
  ::uint32_t raw_thrust;
  memcpy(&raw_thrust, &tmp_thrust, sizeof(tmp_thrust));
  if (raw_thrust != 0) {
    total_size += 5;
  }

  // float steering_yaw = 2;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_yaw = this->_internal_steering_yaw();
  ::uint32_t raw_steering_yaw;
  memcpy(&raw_steering_yaw, &tmp_steering_yaw, sizeof(tmp_steering_yaw));
  if (raw_steering_yaw != 0) {
    total_size += 5;
  }

  // float steering_pitch = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pitch = this->_internal_steering_pitch();
  ::uint32_t raw_steering_pitch;
  memcpy(&raw_steering_pitch, &tmp_steering_pitch, sizeof(tmp_steering_pitch));
  if (raw_steering_pitch != 0) {
    total_size += 5;
  }

  // float steering_roll = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_roll = this->_internal_steering_roll();
  ::uint32_t raw_steering_roll;
  memcpy(&raw_steering_roll, &tmp_steering_roll, sizeof(tmp_steering_roll));
  if (raw_steering_roll != 0) {
    total_size += 5;
  }

  // bool fire = 5;
  if (this->_internal_fire() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgentAction::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgentAction::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgentAction::GetClassData() const { return &_class_data_; }


void AgentAction::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgentAction*>(&to_msg);
  auto& from = static_cast<const AgentAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:fighterrl.AgentAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_thrust = from._internal_thrust();
  ::uint32_t raw_thrust;
  memcpy(&raw_thrust, &tmp_thrust, sizeof(tmp_thrust));
  if (raw_thrust != 0) {
    _this->_internal_set_thrust(from._internal_thrust());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_yaw = from._internal_steering_yaw();
  ::uint32_t raw_steering_yaw;
  memcpy(&raw_steering_yaw, &tmp_steering_yaw, sizeof(tmp_steering_yaw));
  if (raw_steering_yaw != 0) {
    _this->_internal_set_steering_yaw(from._internal_steering_yaw());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_pitch = from._internal_steering_pitch();
  ::uint32_t raw_steering_pitch;
  memcpy(&raw_steering_pitch, &tmp_steering_pitch, sizeof(tmp_steering_pitch));
  if (raw_steering_pitch != 0) {
    _this->_internal_set_steering_pitch(from._internal_steering_pitch());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float), "Code assumes ::uint32_t and float are the same size.");
  float tmp_steering_roll = from._internal_steering_roll();
  ::uint32_t raw_steering_roll;
  memcpy(&raw_steering_roll, &tmp_steering_roll, sizeof(tmp_steering_roll));
  if (raw_steering_roll != 0) {
    _this->_internal_set_steering_roll(from._internal_steering_roll());
  }
  if (from._internal_fire() != 0) {
    _this->_internal_set_fire(from._internal_fire());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgentAction::CopyFrom(const AgentAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:fighterrl.AgentAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgentAction::IsInitialized() const {
  return true;
}

void AgentAction::InternalSwap(AgentAction* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AgentAction, _impl_.fire_)
      + sizeof(AgentAction::_impl_.fire_)
      - PROTOBUF_FIELD_OFFSET(AgentAction, _impl_.thrust_)>(
          reinterpret_cast<char*>(&_impl_.thrust_),
          reinterpret_cast<char*>(&other->_impl_.thrust_));
}

::PROTOBUF_NAMESPACE_ID::Metadata AgentAction::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_FighterRL_2eproto_getter, &descriptor_table_FighterRL_2eproto_once,
      file_level_metadata_FighterRL_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace fighterrl
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::fighterrl::AgentState*
Arena::CreateMaybeMessage< ::fighterrl::AgentState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fighterrl::AgentState >(arena);
}
template<> PROTOBUF_NOINLINE ::fighterrl::AgentAction*
Arena::CreateMaybeMessage< ::fighterrl::AgentAction >(Arena* arena) {
  return Arena::CreateMessageInternal< ::fighterrl::AgentAction >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
