// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: FighterRL.proto

#include "FighterRL.pb.h"
#include "FighterRL.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace fighterrl {

static const char* FighterService_method_names[] = {
  "/fighterrl.FighterService/SendState",
};

std::unique_ptr< FighterService::Stub> FighterService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FighterService::Stub> stub(new FighterService::Stub(channel, options));
  return stub;
}

FighterService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendState_(FighterService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FighterService::Stub::SendState(::grpc::ClientContext* context, const ::fighterrl::AgentState& request, ::fighterrl::AgentAction* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fighterrl::AgentState, ::fighterrl::AgentAction, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendState_, context, request, response);
}

void FighterService::Stub::async::SendState(::grpc::ClientContext* context, const ::fighterrl::AgentState* request, ::fighterrl::AgentAction* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fighterrl::AgentState, ::fighterrl::AgentAction, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendState_, context, request, response, std::move(f));
}

void FighterService::Stub::async::SendState(::grpc::ClientContext* context, const ::fighterrl::AgentState* request, ::fighterrl::AgentAction* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fighterrl::AgentAction>* FighterService::Stub::PrepareAsyncSendStateRaw(::grpc::ClientContext* context, const ::fighterrl::AgentState& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fighterrl::AgentAction, ::fighterrl::AgentState, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fighterrl::AgentAction>* FighterService::Stub::AsyncSendStateRaw(::grpc::ClientContext* context, const ::fighterrl::AgentState& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

FighterService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FighterService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FighterService::Service, ::fighterrl::AgentState, ::fighterrl::AgentAction, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FighterService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fighterrl::AgentState* req,
             ::fighterrl::AgentAction* resp) {
               return service->SendState(ctx, req, resp);
             }, this)));
}

FighterService::Service::~Service() {
}

::grpc::Status FighterService::Service::SendState(::grpc::ServerContext* context, const ::fighterrl::AgentState* request, ::fighterrl::AgentAction* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fighterrl

