#if defined(_MSC_VER)
  #pragma warning (disable:4946) // reinterpret_cast used between related classes: 'class1' and 'class2'
  #pragma warning (disable:4800) // 'type' : forcing value to bool 'true' or 'false' (performance warning)
  #pragma warning (disable:4582) // 'type': constructor is not implicitly called
#endif
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FighterRL.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_FighterRL_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_FighterRL_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_FighterRL_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_FighterRL_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_FighterRL_2eproto;
namespace fighterrl {
class AgentAction;
struct AgentActionDefaultTypeInternal;
extern AgentActionDefaultTypeInternal _AgentAction_default_instance_;
class AgentState;
struct AgentStateDefaultTypeInternal;
extern AgentStateDefaultTypeInternal _AgentState_default_instance_;
}  // namespace fighterrl
PROTOBUF_NAMESPACE_OPEN
template <>
::fighterrl::AgentAction* Arena::CreateMaybeMessage<::fighterrl::AgentAction>(Arena*);
template <>
::fighterrl::AgentState* Arena::CreateMaybeMessage<::fighterrl::AgentState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace fighterrl {

// ===================================================================


// -------------------------------------------------------------------

class AgentState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fighterrl.AgentState) */ {
 public:
  inline AgentState() : AgentState(nullptr) {}
  ~AgentState() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AgentState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgentState(const AgentState& from);
  AgentState(AgentState&& from) noexcept
    : AgentState() {
    *this = ::std::move(from);
  }

  inline AgentState& operator=(const AgentState& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgentState& operator=(AgentState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgentState& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgentState* internal_default_instance() {
    return reinterpret_cast<const AgentState*>(
               &_AgentState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AgentState& a, AgentState& b) {
    a.Swap(&b);
  }
  inline void Swap(AgentState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgentState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgentState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgentState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgentState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AgentState& from) {
    AgentState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgentState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "fighterrl.AgentState";
  }
  protected:
  explicit AgentState(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEnvIdFieldNumber = 1,
    kAgentTypeFieldNumber = 2,
    kTargetTypeFieldNumber = 12,
    kPosXFieldNumber = 3,
    kPosYFieldNumber = 4,
    kPosZFieldNumber = 5,
    kRotYawFieldNumber = 6,
    kRotPitchFieldNumber = 7,
    kRotRollFieldNumber = 8,
    kVelXFieldNumber = 9,
    kVelYFieldNumber = 10,
    kVelZFieldNumber = 11,
    kTargetDistFieldNumber = 13,
    kTargetPosXFieldNumber = 14,
    kTargetPosYFieldNumber = 15,
    kTargetPosZFieldNumber = 16,
    kRewardFieldNumber = 17,
    kDoneFieldNumber = 18,
  };
  // string env_id = 1;
  void clear_env_id() ;
  const std::string& env_id() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_env_id(Arg_&& arg, Args_... args);
  std::string* mutable_env_id();
  PROTOBUF_NODISCARD std::string* release_env_id();
  void set_allocated_env_id(std::string* ptr);

  private:
  const std::string& _internal_env_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_env_id(
      const std::string& value);
  std::string* _internal_mutable_env_id();

  public:
  // string agent_type = 2;
  void clear_agent_type() ;
  const std::string& agent_type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_agent_type(Arg_&& arg, Args_... args);
  std::string* mutable_agent_type();
  PROTOBUF_NODISCARD std::string* release_agent_type();
  void set_allocated_agent_type(std::string* ptr);

  private:
  const std::string& _internal_agent_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_agent_type(
      const std::string& value);
  std::string* _internal_mutable_agent_type();

  public:
  // string target_type = 12;
  void clear_target_type() ;
  const std::string& target_type() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_target_type(Arg_&& arg, Args_... args);
  std::string* mutable_target_type();
  PROTOBUF_NODISCARD std::string* release_target_type();
  void set_allocated_target_type(std::string* ptr);

  private:
  const std::string& _internal_target_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_target_type(
      const std::string& value);
  std::string* _internal_mutable_target_type();

  public:
  // float pos_x = 3;
  void clear_pos_x() ;
  float pos_x() const;
  void set_pos_x(float value);

  private:
  float _internal_pos_x() const;
  void _internal_set_pos_x(float value);

  public:
  // float pos_y = 4;
  void clear_pos_y() ;
  float pos_y() const;
  void set_pos_y(float value);

  private:
  float _internal_pos_y() const;
  void _internal_set_pos_y(float value);

  public:
  // float pos_z = 5;
  void clear_pos_z() ;
  float pos_z() const;
  void set_pos_z(float value);

  private:
  float _internal_pos_z() const;
  void _internal_set_pos_z(float value);

  public:
  // float rot_yaw = 6;
  void clear_rot_yaw() ;
  float rot_yaw() const;
  void set_rot_yaw(float value);

  private:
  float _internal_rot_yaw() const;
  void _internal_set_rot_yaw(float value);

  public:
  // float rot_pitch = 7;
  void clear_rot_pitch() ;
  float rot_pitch() const;
  void set_rot_pitch(float value);

  private:
  float _internal_rot_pitch() const;
  void _internal_set_rot_pitch(float value);

  public:
  // float rot_roll = 8;
  void clear_rot_roll() ;
  float rot_roll() const;
  void set_rot_roll(float value);

  private:
  float _internal_rot_roll() const;
  void _internal_set_rot_roll(float value);

  public:
  // float vel_x = 9;
  void clear_vel_x() ;
  float vel_x() const;
  void set_vel_x(float value);

  private:
  float _internal_vel_x() const;
  void _internal_set_vel_x(float value);

  public:
  // float vel_y = 10;
  void clear_vel_y() ;
  float vel_y() const;
  void set_vel_y(float value);

  private:
  float _internal_vel_y() const;
  void _internal_set_vel_y(float value);

  public:
  // float vel_z = 11;
  void clear_vel_z() ;
  float vel_z() const;
  void set_vel_z(float value);

  private:
  float _internal_vel_z() const;
  void _internal_set_vel_z(float value);

  public:
  // float target_dist = 13;
  void clear_target_dist() ;
  float target_dist() const;
  void set_target_dist(float value);

  private:
  float _internal_target_dist() const;
  void _internal_set_target_dist(float value);

  public:
  // float target_pos_x = 14;
  void clear_target_pos_x() ;
  float target_pos_x() const;
  void set_target_pos_x(float value);

  private:
  float _internal_target_pos_x() const;
  void _internal_set_target_pos_x(float value);

  public:
  // float target_pos_y = 15;
  void clear_target_pos_y() ;
  float target_pos_y() const;
  void set_target_pos_y(float value);

  private:
  float _internal_target_pos_y() const;
  void _internal_set_target_pos_y(float value);

  public:
  // float target_pos_z = 16;
  void clear_target_pos_z() ;
  float target_pos_z() const;
  void set_target_pos_z(float value);

  private:
  float _internal_target_pos_z() const;
  void _internal_set_target_pos_z(float value);

  public:
  // float reward = 17;
  void clear_reward() ;
  float reward() const;
  void set_reward(float value);

  private:
  float _internal_reward() const;
  void _internal_set_reward(float value);

  public:
  // bool done = 18;
  void clear_done() ;
  bool done() const;
  void set_done(bool value);

  private:
  bool _internal_done() const;
  void _internal_set_done(bool value);

  public:
  // @@protoc_insertion_point(class_scope:fighterrl.AgentState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr env_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr agent_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr target_type_;
    float pos_x_;
    float pos_y_;
    float pos_z_;
    float rot_yaw_;
    float rot_pitch_;
    float rot_roll_;
    float vel_x_;
    float vel_y_;
    float vel_z_;
    float target_dist_;
    float target_pos_x_;
    float target_pos_y_;
    float target_pos_z_;
    float reward_;
    bool done_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FighterRL_2eproto;
};// -------------------------------------------------------------------

class AgentAction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fighterrl.AgentAction) */ {
 public:
  inline AgentAction() : AgentAction(nullptr) {}
  ~AgentAction() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AgentAction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgentAction(const AgentAction& from);
  AgentAction(AgentAction&& from) noexcept
    : AgentAction() {
    *this = ::std::move(from);
  }

  inline AgentAction& operator=(const AgentAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgentAction& operator=(AgentAction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgentAction& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgentAction* internal_default_instance() {
    return reinterpret_cast<const AgentAction*>(
               &_AgentAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(AgentAction& a, AgentAction& b) {
    a.Swap(&b);
  }
  inline void Swap(AgentAction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgentAction* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgentAction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgentAction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgentAction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AgentAction& from) {
    AgentAction::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgentAction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "fighterrl.AgentAction";
  }
  protected:
  explicit AgentAction(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kThrustFieldNumber = 1,
    kSteeringYawFieldNumber = 2,
    kSteeringPitchFieldNumber = 3,
    kSteeringRollFieldNumber = 4,
    kFireFieldNumber = 5,
  };
  // float thrust = 1;
  void clear_thrust() ;
  float thrust() const;
  void set_thrust(float value);

  private:
  float _internal_thrust() const;
  void _internal_set_thrust(float value);

  public:
  // float steering_yaw = 2;
  void clear_steering_yaw() ;
  float steering_yaw() const;
  void set_steering_yaw(float value);

  private:
  float _internal_steering_yaw() const;
  void _internal_set_steering_yaw(float value);

  public:
  // float steering_pitch = 3;
  void clear_steering_pitch() ;
  float steering_pitch() const;
  void set_steering_pitch(float value);

  private:
  float _internal_steering_pitch() const;
  void _internal_set_steering_pitch(float value);

  public:
  // float steering_roll = 4;
  void clear_steering_roll() ;
  float steering_roll() const;
  void set_steering_roll(float value);

  private:
  float _internal_steering_roll() const;
  void _internal_set_steering_roll(float value);

  public:
  // bool fire = 5;
  void clear_fire() ;
  bool fire() const;
  void set_fire(bool value);

  private:
  bool _internal_fire() const;
  void _internal_set_fire(bool value);

  public:
  // @@protoc_insertion_point(class_scope:fighterrl.AgentAction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float thrust_;
    float steering_yaw_;
    float steering_pitch_;
    float steering_roll_;
    bool fire_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FighterRL_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AgentState

// string env_id = 1;
inline void AgentState::clear_env_id() {
  _impl_.env_id_.ClearToEmpty();
}
inline const std::string& AgentState::env_id() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.env_id)
  return _internal_env_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AgentState::set_env_id(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.env_id_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.env_id)
}
inline std::string* AgentState::mutable_env_id() {
  std::string* _s = _internal_mutable_env_id();
  // @@protoc_insertion_point(field_mutable:fighterrl.AgentState.env_id)
  return _s;
}
inline const std::string& AgentState::_internal_env_id() const {
  return _impl_.env_id_.Get();
}
inline void AgentState::_internal_set_env_id(const std::string& value) {
  ;


  _impl_.env_id_.Set(value, GetArenaForAllocation());
}
inline std::string* AgentState::_internal_mutable_env_id() {
  ;
  return _impl_.env_id_.Mutable( GetArenaForAllocation());
}
inline std::string* AgentState::release_env_id() {
  // @@protoc_insertion_point(field_release:fighterrl.AgentState.env_id)
  return _impl_.env_id_.Release();
}
inline void AgentState::set_allocated_env_id(std::string* value) {
  _impl_.env_id_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.env_id_.IsDefault()) {
          _impl_.env_id_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fighterrl.AgentState.env_id)
}

// string agent_type = 2;
inline void AgentState::clear_agent_type() {
  _impl_.agent_type_.ClearToEmpty();
}
inline const std::string& AgentState::agent_type() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.agent_type)
  return _internal_agent_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AgentState::set_agent_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.agent_type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.agent_type)
}
inline std::string* AgentState::mutable_agent_type() {
  std::string* _s = _internal_mutable_agent_type();
  // @@protoc_insertion_point(field_mutable:fighterrl.AgentState.agent_type)
  return _s;
}
inline const std::string& AgentState::_internal_agent_type() const {
  return _impl_.agent_type_.Get();
}
inline void AgentState::_internal_set_agent_type(const std::string& value) {
  ;


  _impl_.agent_type_.Set(value, GetArenaForAllocation());
}
inline std::string* AgentState::_internal_mutable_agent_type() {
  ;
  return _impl_.agent_type_.Mutable( GetArenaForAllocation());
}
inline std::string* AgentState::release_agent_type() {
  // @@protoc_insertion_point(field_release:fighterrl.AgentState.agent_type)
  return _impl_.agent_type_.Release();
}
inline void AgentState::set_allocated_agent_type(std::string* value) {
  _impl_.agent_type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.agent_type_.IsDefault()) {
          _impl_.agent_type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fighterrl.AgentState.agent_type)
}

// float pos_x = 3;
inline void AgentState::clear_pos_x() {
  _impl_.pos_x_ = 0;
}
inline float AgentState::pos_x() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.pos_x)
  return _internal_pos_x();
}
inline void AgentState::set_pos_x(float value) {
  _internal_set_pos_x(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.pos_x)
}
inline float AgentState::_internal_pos_x() const {
  return _impl_.pos_x_;
}
inline void AgentState::_internal_set_pos_x(float value) {
  ;
  _impl_.pos_x_ = value;
}

// float pos_y = 4;
inline void AgentState::clear_pos_y() {
  _impl_.pos_y_ = 0;
}
inline float AgentState::pos_y() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.pos_y)
  return _internal_pos_y();
}
inline void AgentState::set_pos_y(float value) {
  _internal_set_pos_y(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.pos_y)
}
inline float AgentState::_internal_pos_y() const {
  return _impl_.pos_y_;
}
inline void AgentState::_internal_set_pos_y(float value) {
  ;
  _impl_.pos_y_ = value;
}

// float pos_z = 5;
inline void AgentState::clear_pos_z() {
  _impl_.pos_z_ = 0;
}
inline float AgentState::pos_z() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.pos_z)
  return _internal_pos_z();
}
inline void AgentState::set_pos_z(float value) {
  _internal_set_pos_z(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.pos_z)
}
inline float AgentState::_internal_pos_z() const {
  return _impl_.pos_z_;
}
inline void AgentState::_internal_set_pos_z(float value) {
  ;
  _impl_.pos_z_ = value;
}

// float rot_yaw = 6;
inline void AgentState::clear_rot_yaw() {
  _impl_.rot_yaw_ = 0;
}
inline float AgentState::rot_yaw() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.rot_yaw)
  return _internal_rot_yaw();
}
inline void AgentState::set_rot_yaw(float value) {
  _internal_set_rot_yaw(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.rot_yaw)
}
inline float AgentState::_internal_rot_yaw() const {
  return _impl_.rot_yaw_;
}
inline void AgentState::_internal_set_rot_yaw(float value) {
  ;
  _impl_.rot_yaw_ = value;
}

// float rot_pitch = 7;
inline void AgentState::clear_rot_pitch() {
  _impl_.rot_pitch_ = 0;
}
inline float AgentState::rot_pitch() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.rot_pitch)
  return _internal_rot_pitch();
}
inline void AgentState::set_rot_pitch(float value) {
  _internal_set_rot_pitch(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.rot_pitch)
}
inline float AgentState::_internal_rot_pitch() const {
  return _impl_.rot_pitch_;
}
inline void AgentState::_internal_set_rot_pitch(float value) {
  ;
  _impl_.rot_pitch_ = value;
}

// float rot_roll = 8;
inline void AgentState::clear_rot_roll() {
  _impl_.rot_roll_ = 0;
}
inline float AgentState::rot_roll() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.rot_roll)
  return _internal_rot_roll();
}
inline void AgentState::set_rot_roll(float value) {
  _internal_set_rot_roll(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.rot_roll)
}
inline float AgentState::_internal_rot_roll() const {
  return _impl_.rot_roll_;
}
inline void AgentState::_internal_set_rot_roll(float value) {
  ;
  _impl_.rot_roll_ = value;
}

// float vel_x = 9;
inline void AgentState::clear_vel_x() {
  _impl_.vel_x_ = 0;
}
inline float AgentState::vel_x() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.vel_x)
  return _internal_vel_x();
}
inline void AgentState::set_vel_x(float value) {
  _internal_set_vel_x(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.vel_x)
}
inline float AgentState::_internal_vel_x() const {
  return _impl_.vel_x_;
}
inline void AgentState::_internal_set_vel_x(float value) {
  ;
  _impl_.vel_x_ = value;
}

// float vel_y = 10;
inline void AgentState::clear_vel_y() {
  _impl_.vel_y_ = 0;
}
inline float AgentState::vel_y() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.vel_y)
  return _internal_vel_y();
}
inline void AgentState::set_vel_y(float value) {
  _internal_set_vel_y(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.vel_y)
}
inline float AgentState::_internal_vel_y() const {
  return _impl_.vel_y_;
}
inline void AgentState::_internal_set_vel_y(float value) {
  ;
  _impl_.vel_y_ = value;
}

// float vel_z = 11;
inline void AgentState::clear_vel_z() {
  _impl_.vel_z_ = 0;
}
inline float AgentState::vel_z() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.vel_z)
  return _internal_vel_z();
}
inline void AgentState::set_vel_z(float value) {
  _internal_set_vel_z(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.vel_z)
}
inline float AgentState::_internal_vel_z() const {
  return _impl_.vel_z_;
}
inline void AgentState::_internal_set_vel_z(float value) {
  ;
  _impl_.vel_z_ = value;
}

// string target_type = 12;
inline void AgentState::clear_target_type() {
  _impl_.target_type_.ClearToEmpty();
}
inline const std::string& AgentState::target_type() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.target_type)
  return _internal_target_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AgentState::set_target_type(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.target_type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.target_type)
}
inline std::string* AgentState::mutable_target_type() {
  std::string* _s = _internal_mutable_target_type();
  // @@protoc_insertion_point(field_mutable:fighterrl.AgentState.target_type)
  return _s;
}
inline const std::string& AgentState::_internal_target_type() const {
  return _impl_.target_type_.Get();
}
inline void AgentState::_internal_set_target_type(const std::string& value) {
  ;


  _impl_.target_type_.Set(value, GetArenaForAllocation());
}
inline std::string* AgentState::_internal_mutable_target_type() {
  ;
  return _impl_.target_type_.Mutable( GetArenaForAllocation());
}
inline std::string* AgentState::release_target_type() {
  // @@protoc_insertion_point(field_release:fighterrl.AgentState.target_type)
  return _impl_.target_type_.Release();
}
inline void AgentState::set_allocated_target_type(std::string* value) {
  _impl_.target_type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.target_type_.IsDefault()) {
          _impl_.target_type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:fighterrl.AgentState.target_type)
}

// float target_dist = 13;
inline void AgentState::clear_target_dist() {
  _impl_.target_dist_ = 0;
}
inline float AgentState::target_dist() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.target_dist)
  return _internal_target_dist();
}
inline void AgentState::set_target_dist(float value) {
  _internal_set_target_dist(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.target_dist)
}
inline float AgentState::_internal_target_dist() const {
  return _impl_.target_dist_;
}
inline void AgentState::_internal_set_target_dist(float value) {
  ;
  _impl_.target_dist_ = value;
}

// float target_pos_x = 14;
inline void AgentState::clear_target_pos_x() {
  _impl_.target_pos_x_ = 0;
}
inline float AgentState::target_pos_x() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.target_pos_x)
  return _internal_target_pos_x();
}
inline void AgentState::set_target_pos_x(float value) {
  _internal_set_target_pos_x(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.target_pos_x)
}
inline float AgentState::_internal_target_pos_x() const {
  return _impl_.target_pos_x_;
}
inline void AgentState::_internal_set_target_pos_x(float value) {
  ;
  _impl_.target_pos_x_ = value;
}

// float target_pos_y = 15;
inline void AgentState::clear_target_pos_y() {
  _impl_.target_pos_y_ = 0;
}
inline float AgentState::target_pos_y() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.target_pos_y)
  return _internal_target_pos_y();
}
inline void AgentState::set_target_pos_y(float value) {
  _internal_set_target_pos_y(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.target_pos_y)
}
inline float AgentState::_internal_target_pos_y() const {
  return _impl_.target_pos_y_;
}
inline void AgentState::_internal_set_target_pos_y(float value) {
  ;
  _impl_.target_pos_y_ = value;
}

// float target_pos_z = 16;
inline void AgentState::clear_target_pos_z() {
  _impl_.target_pos_z_ = 0;
}
inline float AgentState::target_pos_z() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.target_pos_z)
  return _internal_target_pos_z();
}
inline void AgentState::set_target_pos_z(float value) {
  _internal_set_target_pos_z(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.target_pos_z)
}
inline float AgentState::_internal_target_pos_z() const {
  return _impl_.target_pos_z_;
}
inline void AgentState::_internal_set_target_pos_z(float value) {
  ;
  _impl_.target_pos_z_ = value;
}

// float reward = 17;
inline void AgentState::clear_reward() {
  _impl_.reward_ = 0;
}
inline float AgentState::reward() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.reward)
  return _internal_reward();
}
inline void AgentState::set_reward(float value) {
  _internal_set_reward(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.reward)
}
inline float AgentState::_internal_reward() const {
  return _impl_.reward_;
}
inline void AgentState::_internal_set_reward(float value) {
  ;
  _impl_.reward_ = value;
}

// bool done = 18;
inline void AgentState::clear_done() {
  _impl_.done_ = false;
}
inline bool AgentState::done() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentState.done)
  return _internal_done();
}
inline void AgentState::set_done(bool value) {
  _internal_set_done(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentState.done)
}
inline bool AgentState::_internal_done() const {
  return _impl_.done_;
}
inline void AgentState::_internal_set_done(bool value) {
  ;
  _impl_.done_ = value;
}

// -------------------------------------------------------------------

// AgentAction

// float thrust = 1;
inline void AgentAction::clear_thrust() {
  _impl_.thrust_ = 0;
}
inline float AgentAction::thrust() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentAction.thrust)
  return _internal_thrust();
}
inline void AgentAction::set_thrust(float value) {
  _internal_set_thrust(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentAction.thrust)
}
inline float AgentAction::_internal_thrust() const {
  return _impl_.thrust_;
}
inline void AgentAction::_internal_set_thrust(float value) {
  ;
  _impl_.thrust_ = value;
}

// float steering_yaw = 2;
inline void AgentAction::clear_steering_yaw() {
  _impl_.steering_yaw_ = 0;
}
inline float AgentAction::steering_yaw() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentAction.steering_yaw)
  return _internal_steering_yaw();
}
inline void AgentAction::set_steering_yaw(float value) {
  _internal_set_steering_yaw(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentAction.steering_yaw)
}
inline float AgentAction::_internal_steering_yaw() const {
  return _impl_.steering_yaw_;
}
inline void AgentAction::_internal_set_steering_yaw(float value) {
  ;
  _impl_.steering_yaw_ = value;
}

// float steering_pitch = 3;
inline void AgentAction::clear_steering_pitch() {
  _impl_.steering_pitch_ = 0;
}
inline float AgentAction::steering_pitch() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentAction.steering_pitch)
  return _internal_steering_pitch();
}
inline void AgentAction::set_steering_pitch(float value) {
  _internal_set_steering_pitch(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentAction.steering_pitch)
}
inline float AgentAction::_internal_steering_pitch() const {
  return _impl_.steering_pitch_;
}
inline void AgentAction::_internal_set_steering_pitch(float value) {
  ;
  _impl_.steering_pitch_ = value;
}

// float steering_roll = 4;
inline void AgentAction::clear_steering_roll() {
  _impl_.steering_roll_ = 0;
}
inline float AgentAction::steering_roll() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentAction.steering_roll)
  return _internal_steering_roll();
}
inline void AgentAction::set_steering_roll(float value) {
  _internal_set_steering_roll(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentAction.steering_roll)
}
inline float AgentAction::_internal_steering_roll() const {
  return _impl_.steering_roll_;
}
inline void AgentAction::_internal_set_steering_roll(float value) {
  ;
  _impl_.steering_roll_ = value;
}

// bool fire = 5;
inline void AgentAction::clear_fire() {
  _impl_.fire_ = false;
}
inline bool AgentAction::fire() const {
  // @@protoc_insertion_point(field_get:fighterrl.AgentAction.fire)
  return _internal_fire();
}
inline void AgentAction::set_fire(bool value) {
  _internal_set_fire(value);
  // @@protoc_insertion_point(field_set:fighterrl.AgentAction.fire)
}
inline bool AgentAction::_internal_fire() const {
  return _impl_.fire_;
}
inline void AgentAction::_internal_set_fire(bool value) {
  ;
  _impl_.fire_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace fighterrl


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_FighterRL_2eproto_2epb_2eh
